spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/uspokajamlek
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create

jwt:
  secret: DOSJNDSDSAOJNK$O#QUJNK131234142142
  expiration: 1000000