version: "3.8"

services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=uspokajamlek
    ports:
      - '5432:5432'

  backend:
    container_name: uspokajam_lek_backend
    build:
      context: .
      dockerfile: Uspokajam-lek-backend/Dockerfile
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/uspokajamlek
    depends_on:
      - psql-db

  frontend:
    container_name: uspokajam_lek_frontend
    build:
      context: .
      dockerfile: Uspokajam-lek-frontend/Dockerfile
    ports:
      - '4200:4200'
